name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # TODO: check versions

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      # npm ci is similar to npm install, expect it is meant to be used in automated environments
      - name: Run tests
        run: npm run test
      - name: Run prettier
        run: npm run format
      - name: Run TypeScript type check
        run: npx tsc -b --noEmit # Directly run tsc without needing an npm script
      - name: Build the project
        run: npm run build --if-present
